tasks:
  - init: "(mkdir build; cd build; cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1 ..);cp build/compile_commands.json ."
    command: exec zsh
image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - xaver.clang-format@1.9.0:auCYfQ5pnsZ6Cjf4ZxkAtA==